name: Docker Image CI

on:
  push:
    branches: [ "ayomide_submission" ]
  pull_request:
    branches: ["ayomide_submission"]

jobs:

  build:

    runs-on: ubuntu-latest
		
    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
			
    - name: Build the Docker image
      run: docker build -t brazil_order_ayomide-api-deployment .
    - name: Push to Dockerhub
      run: docker push dammy230/brazil_order_ayomide-api-deployment:latest
